-- ==========================================================
-- AaaS Handmade Crochet - Production Product Catalog Seed
-- Architecture: CraftyMinds-like Simplified Schema
-- Inserts canonical product catalog with direct category and image_url attributes
-- Uses valid RFC 4122 hexadecimal UUIDs
-- ==========================================================

INSERT INTO public.products (
    id, name, slug, description, price, sale_price, compare_at_price,
    category, image_url, images, stock_quantity, inventory_count,
    low_stock_threshold, sku, tags, is_active, is_featured, is_bestseller, is_new
)
VALUES
    (
        '01111111-1111-1111-1111-111111111111',
        'Crochet Tulip Bouquet',
        'crochet-tulip-bouquet',
        'An enchanting bouquet of handcrafted crochet tulips in delicate shades of soft blush, warm ivory, and gentle peach. Each bloom is individually crocheted from premium milk cotton yarn with flexible wire-reinforced stems, wrapped in eco-conscious kraft paper with an antique gold ribbon tie. A timeless gift that never withers.',
        999.00,
        899.00,
        899.00,
        'Crochet Flowers & Bouquets',
        '/images/tulip_bouquet.jpg',
        ARRAY['/images/tulip_bouquet.jpg', '/images/hero_lifestyle.jpg'],
        12,
        12,
        3,
        'AAAS-P11111',
        ARRAY['tulips', 'bouquet', 'flowers', 'gift', 'bestseller'],
        true,
        true,
        true,
        true
    ),
    (
        '02222222-2222-2222-2222-222222222222',
        'Crochet Mini Handbag',
        'crochet-mini-handbag',
        'Crafted for modern elegance, this chunky-knit artisan handbag features a warm ivory and taupe weave, sturdy structured bamboo top handles, and a soft cotton interior. Perfectly sized to hold your essentials—phone, keys, compact wallet, and lip balm—while adding a warm, handcrafted statement to any outfit.',
        1499.00,
        1299.00,
        1299.00,
        'Handbags',
        '/images/mini_handbag.jpg',
        ARRAY['/images/mini_handbag.jpg', '/images/hero_lifestyle.jpg'],
        8,
        8,
        2,
        'AAAS-P22222',
        ARRAY['handbag', 'tote', 'bamboo', 'luxury', 'chic'],
        true,
        true,
        true,
        true
    ),
    (
        '03333333-3333-3333-3333-333333333333',
        'Crochet Daisy Bouquet',
        'crochet-daisy-bouquet',
        'A cheerful yet elegant arrangement of bright white crochet daisies with golden textured sunburst centers and delicate sage green foliage. Lovingly tied with an organic linen ribbon, this bouquet brings warm, sunny craftsmanship into any room.',
        999.00,
        NULL,
        NULL,
        'Crochet Flowers & Bouquets',
        '/images/daisy_bouquet.jpg',
        ARRAY['/images/daisy_bouquet.jpg', '/images/artisan_hands.jpg'],
        15,
        15,
        3,
        'AAAS-P33333',
        ARRAY['daisy', 'flowers', 'sage', 'gift', 'nature'],
        true,
        true,
        false,
        true
    ),
    (
        '04444444-4444-4444-4444-444444444444',
        'Crochet Flower Coaster Set',
        'crochet-flower-coaster',
        'Set of 4 artisan botanical coasters handcrafted in harmonious tones of sage green, ivory cream, and warm taupe. Thick, heat-resistant, and absorbent, these coasters protect your tabletops while bringing warmth and organic beauty to your coffee and tea rituals.',
        250.00,
        249.00,
        249.00,
        'Accessories',
        '/images/flower_coaster.jpg',
        ARRAY['/images/flower_coaster.jpg'],
        25,
        25,
        5,
        'AAAS-P44444',
        ARRAY['coasters', 'home decor', 'accessories', 'tableware', 'botanical'],
        true,
        false,
        true,
        false
    ),
    (
        '05555555-5555-5555-5555-555555555555',
        'Crochet Keychain & Charm Set',
        'crochet-keychain-charm-set',
        'An adorable trio of mini handcrafted accessories: a sweet crochet strawberry charm, a soft peach keyring, and a delicate floral scrunchie. Finished with durable antique gold metal lobster clasps to clip effortlessly onto bags, keys, or pouches.',
        199.00,
        249.00,
        249.00,
        'Accessories',
        '/images/keychain_charms.jpg',
        ARRAY['/images/keychain_charms.jpg'],
        30,
        30,
        5,
        'AAAS-P55555',
        ARRAY['keychain', 'accessories', 'charms', 'strawberry', 'scrunchie'],
        true,
        false,
        true,
        true
    ),
    (
        '06666666-6666-6666-6666-666666666666',
        'Bespoke Personalized Crochet Piece',
        'bespoke-custom-crochet-piece',
        'Have a dream crochet design in mind? Collaborate directly with our master artisan to create custom bridal bouquets, heirloom baby blankets, bespoke color-matched handbags, or unique decor pieces. Price starts as a base deposit and adjusts according to your requirements.',
        1499.00,
        NULL,
        NULL,
        'Custom Orders',
        '/images/custom_banner.jpg',
        ARRAY['/images/custom_banner.jpg'],
        99,
        99,
        5,
        'AAAS-P66666',
        ARRAY['custom', 'bespoke', 'personalized', 'artisan', 'special'],
        true,
        true,
        false,
        true
    )
ON CONFLICT (slug) DO UPDATE SET
    category = EXCLUDED.category,
    image_url = EXCLUDED.image_url,
    images = EXCLUDED.images,
    price = EXCLUDED.price,
    sale_price = EXCLUDED.sale_price,
    compare_at_price = EXCLUDED.compare_at_price,
    stock_quantity = EXCLUDED.stock_quantity,
    inventory_count = EXCLUDED.inventory_count,
    is_active = EXCLUDED.is_active,
    is_featured = EXCLUDED.is_featured,
    is_bestseller = EXCLUDED.is_bestseller,
    is_new = EXCLUDED.is_new,
    updated_at = now();
